spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/scott?
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: scott
    password: tiger

  mail:
    host: smtp.gmail.com
    port: 587
    username:  # \uC774\uBA54\uC77C
    password:  # APP \uBE44\uBC00\uBC88\uD638
    properties:
      mail:
        smtp:
          auth: true # \uC778\uC99D
          starttls:
            enable: true
  redis:
    host: localhost
    port: 6379
    password: 1234

  jwt:
    secret: k80pSiDFvA4kSpHX4TklloHRHsPJoH4OGIfr9XbwmBM2Bkad8n # \uC2DC\uD06C\uB9BF \uD0A4
    access-expiration_time: 1800000  # 30\uBD84
    refresh-expiration_time: 86400000 # 1\uC77C

server:
  port: 8099
  servlet:
    session:
      timeout: 1800

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
        transaction: DEBUG
    com:
      .zaxxer: DEBUG
    sql: DEBUG

