spring:
  config:
    import:
      - api.yml
      - database.yml

server:
  port: 8099
  servlet:
    session:
      timeout: 1800

logging:
  level:
    org.springframework: INFO
    com.multi.laptellect: DEBUG

    sql: DEBUG
    jdbc.audit: ERROR
    jdbc.sqlonly: ERROR
    jdbc.sqltiming: ERROR
    jdbc.resultset: ERROR
    jdbc.resultsettable: DEBUG