spring:
  datasource:
    url: jdbc:mysql://localhost:3306/final
    #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: mysql


  mail:
    host: smtp.gmail.com
    port: 587
    username: filmpick123@gmail.com # \uC774\uBA54\uC77C
    password: jxsccjcjrgutlxwy # APP \uBE44\uBC00\uBC88\uD638
    properties:
      mail:
        smtp:
          auth: true # \uC778\uC99D
          starttls:
            enable: true
  redis:
    host: localhost
    port: 6379
    password: 1234


server:
  port: 8099
  servlet:
    session:
      timeout: 1800


logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
        transaction: DEBUG
    com:
      .zaxxer: DEBUG
    sql: DEBUG

