#redis:
#  host: localhost
#  port: 6379
#  password: 1234
#
#mail:
#  host: smtp.gmail.com
#  port: 587
#  username: ckatnfl1234@gmail.com
#  password: sjzhdwackhueuoce # APP \uBE44\uBC00\uBC88\uD638
#  properties:
#    mail:
#      smtp:
#        auth: true # \uC778\uC99D
#        starttls:
#          enable: true
#
#coolsms:
#  api:
#    key: NCSJX8SJCCALFXZ6
#    secret: F0WFPI4WRVMRJJP5SNEDGGAE9LNSEO0J
#  caller: 01092526582

#kakao:
#  key: 2260d1ff32638c0b096300eec96b9386
#  redirect: http://localhost:8099/signin/oauth/kakao