spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scott
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: scott
    password: tiger

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username:  # \uC774\uBA54\uC77C
#    password:  # APP \uBE44\uBC00\uBC88\uD638
#    properties:
#      mail:
#        smtp:
#          auth: true # \uC778\uC99D
#          starttls:
#            enable: true

server:
  port: 8099
  servlet:
    session:
      timeout: 1800


#logging:
#  level:
#    org:
#      springframework:
#        jdbc: DEBUG
#        transaction: DEBUG
#    com:
#      .zaxxer: DEBUG
#    sql: DEBUG