spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/scott?
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: scott
    password: tiger
  redis:
    host: localhost
    port: 6379
    password: 1234
