spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/final
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: mysql
  redis:
    host: localhost
    port: 6379
    password: 1234