name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Set up JDK 17
        id: setup-java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate configuration files
        run: |
          echo "Generating api.yml..."
          cat << EOF > src/main/resources/api.yml
          spring:
            mail:
              host: smtp.gmail.com
              port: 587
              username: \${{ secrets.GMAIL_USERNAME }}
              password: \${{ secrets.GMAIL_PASSWORD }}
              properties:
                mail:
                  smtp:
                    auth: true
                    starttls:
                      enable: true
            coolsms:
              api:
                key: \${{ secrets.COOLSMS_API_KEY }}
                secret: \${{ secrets.COOLSMS_API_SECRET }}
              caller: \${{ secrets.COOLSMS_CALLER }}
            google:
              key: \${{ secrets.GOOGLE_API_KEY }}
              client-id: \${{ secrets.GOOGLE_CLIENT_ID }}
              client-secret: \${{ secrets.GOOGLE_CLIENT_SECRET }}
              redirect: http://laptelect.n-e.kr:8099/signin/oauth/google
            kakao:
              admin-key: \${{ secrets.KAKAO_ADMIN_KEY }}
              key: \${{ secrets.KAKAO_KEY }}
              rest-key: \${{ secrets.KAKAO_REST_KEY }}
              secret-key: \${{ secrets.KAKAO_SECRET_KEY }}
              redirect: http://laptelect.n-e.kr:8099/signin/oauth/kakao
            data:
              base-url: https://api.odcloud.kr/api/nts-businessman/v1/validate?serviceKey=
              api:
                business-registration-number:
                  api-key: \${{ secrets.DATA_API_KEY }}
            ncp:
              accessKey: \${{ secrets.NCP_ACCESS_KEY }}
              secretKey: \${{ secrets.NCP_SECRET_KEY }}
              s3:
                bucket: 4team
              chatbot:
                url: https://47rv9xlkxz.apigw.ntruss.com/custom/v1/15392/fb96048ba2e6e2690fd8290fc72fbc4bc69b76708e595f017e203fda2f18997c
                key: \${{ secrets.NCP_CHATBOT_KEY }}
            iamport:
              api-key: \${{ secrets.IAMPORT_API_KEY }}
              api-secret: \${{ secrets.IAMPORT_API_SECRET }}
            sentiment:
              clientId: \${{ secrets.SENTIMENT_CLIENT_ID }}
              clientSecret: \${{ secrets.SENTIMENT_CLIENT_SECRET }}
          EOF
          echo "Generating database.yml..."
          cat << EOF > src/main/resources/database.yml
          spring:
            datasource:
              url: jdbc:log4jdbc:mysql://db-ou0r9.pub-cdb.ntruss.com:3306/team4?
              driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
              username: \${{ secrets.DATASOURCE_USERNAME }}
              password: \${{ secrets.DATASOURCE_PASSWORD }}
            redis:
              host: \${{ secrets.REDIS_HOST }}
              port: \${{ secrets.REDIS_PORT }}
              password: \${{ secrets.REDIS_PASSWORD }}
          EOF
      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew
        
      - name: Build with Gradle
        run: |
          # Ensure JAVA_HOME is set to JDK 17
          export JAVA_HOME="${{ steps.setup-java.outputs.java-home }}"
          export PATH="$JAVA_HOME/bin:$PATH"
          java -version
          ./gradlew build --warning-mode all
      
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: build/reports/tests/test/index.html

      - name: Upload Gradle Build Log
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: gradle-log
          path: gradle.log
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: cpfur18/laptellcet:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            docker pull cpfur18/laptellcet:latest
            docker-compose down
            docker-compose up -d
